export interface ChangelogEntry {
  version: string;
  date: string; // ISO date
  title: string;
  changes: string[];
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: "1.24.0",
    date: "2026-07-29",
    title: "Reach & Offer dan Anggota EA kini benar-benar terpisah per Ormawa Visit",
    changes: [
      "PERBAIKAN: seluruh 61 data Reach & Offer tersimpan tanpa penanda Ormawa Visit, sehingga setiap edisi menampilkan semuanya — padahal miliknya sendiri hanya 12–19. Sekarang tiap prospek terikat ke edisinya: OV1 2025 punya 19, OV2 2025 punya 16, OV1 2026 punya 12, OV2 2026 punya 14.",
      "PERBAIKAN: 44 anggota EA juga tersimpan tanpa penanda Ormawa Visit dan ikut muncul di semua edisi. Daftar anggota kini memakai roster asli per edisi — OV1 2025: 17 orang, OV2 2025: 44, OV1 2026: 15, OV2 2026: 43.",
      "Skrip pembuat data awal sekarang MENOLAK berjalan kalau ada prospek tanpa Ormawa Visit, dan tidak lagi menulis anggota tanpa edisi. Jadi kebocoran seperti ini tidak bisa masuk lagi lewat pintu yang sama.",
      "Panduan rebuild data diperbarui: setelah data awal, wajib menjalankan skrip roster asli supaya daftar divisi, anggota, dan tim terisi per edisi.",
    ],
  },
  {
    version: "1.23.0",
    date: "2026-07-29",
    title: "Rebuild data bersih, 60 terjemahan Inggris, changelog dilipat & Tamu bisa buka Pengaturan",
    changes: [
      "AKAR MASALAH DUPLIKAT DITEMUKAN: skrip data awal (seed.sql) berisi 529 perintah tambah-data tanpa pengaman anti-kembar, jadi menjalankannya dua kali menggandakan hampir semua tabel. Ini bukan bug aplikasi — dan tidak akan hilang hanya dengan membersihkan sebagian.",
      "Tersedia skrip 'reset-data.sql' untuk mengosongkan seluruh data Ormawa Visit lalu mengisinya ulang sekali saja. Akun, peran, dan riwayat backup TIDAK terhapus, jadi tidak ada yang perlu mendaftar ulang. Panduan langkahnya ada di supabase/README.md.",
      "PERBAIKAN: fitur gabung sel Rundown gagal dengan pesan \"Could not find the 'merges' column\" karena kolomnya belum ada di skrip skema utama. Sekarang sudah termasuk, jadi ikut terpasang saat menyiapkan database.",
      "60 teks yang masih berbahasa Indonesia saat bahasa diatur ke English kini diterjemahkan — terutama seluruh diagram alur di menu Panduan, dialog Edit, pesan 'belum ada data', dan tombol Reset Mode Demo.",
      "Ditambahkan pemeriksaan otomatis yang menolak teks baru tanpa terjemahan, supaya kekurangan seperti ini tidak menumpuk lagi.",
      "Changelog di Pengaturan kini menampilkan 5 versi terbaru saja, dengan tombol 'Lihat semua versi' untuk membuka sisanya.",
      "Peran Tamu sekarang bisa membuka menu Pengaturan (matriks hak akses, arsip spreadsheet, changelog, versi) — tetap hanya lihat. Kartu Backup & Rollback dan Reset Data Demo tidak muncul untuk Tamu.",
    ],
  },
  {
    version: "1.22.0",
    date: "2026-07-29",
    title: "Performance Measurement, gabung sel rundown, arsip spreadsheet & impor Super Link",
    changes: [
      "BARU — Performance Measurement di Dashboard: jumlah fungsionaris HMSI yang hadir, total feedback dari HMSI dan dari himpunan partner, rata-rata ratingnya dalam bentuk bintang (misal 4.78/5.0), serta tautan Laporan Pertanggung Jawaban. Diisi lewat menu Ormawa Visit → Edit, dan setiap Ormawa Visit punya datanya sendiri.",
      "Kolom yang belum diisi ditampilkan sebagai '—', bukan angka nol — supaya 'belum ada data' tidak tertukar dengan 'nilainya memang nol'.",
      "BARU — Gabung sel di Rundown: kolom MC, Kebutuhan Operator, dan semua kolom divisi bisa digabung ke baris di bawahnya, untuk menunjukkan satu kegiatan yang berjalan melintasi beberapa slot waktu. Arahkan kursor ke selnya, lalu klik ikon gabung; ikon di sebelahnya memisahkan kembali. Kolom Catatan sengaja tidak bisa digabung karena isinya khas per baris.",
      "BARU — Arsip Spreadsheet di Pengaturan: tautan ke Main Sheet asli 2024, 2025, dan 2026 sebagai rujukan riwayat sebelum sistem ini ada.",
      "Super Link diperbarui dari Main Sheet terbaru: 87 tautan disegarkan atau ditambahkan di keempat Ormawa Visit. Tautan yang kamu buat sendiri lewat aplikasi tidak ikut tertimpa.",
      "PERBAIKAN: baris duplikat yang muncul karena skrip SQL sempat dijalankan lebih dari sekali kini bisa dibersihkan. Yang dibuang hanya salinan yang benar-benar identik — data yang mirip tapi berbeda (misal judul tugas sama dengan PIC berbeda) tetap aman.",
      "PERBAIKAN: kotak tanggal pada timeline tidak lagi tertutup bilah atas ketika ada spanduk Mode Demo atau Arsip. Posisinya kini mengikuti tinggi bilah yang sebenarnya.",
    ],
  },
  {
    version: "1.21.0",
    date: "2026-07-28",
    title: "Pencarian di tengah layar, riwayat pencarian, penanda arsip & perbaikan timeline",
    changes: [
      "Pop-up pencarian kini muncul tepat di tengah layar dengan latar belakang yang diburamkan, dan bisa ditutup lewat tombol X selain tombol Esc.",
      "Pencarian menyimpan riwayat: begitu dibuka, daftar 'Pencarian terakhir' langsung tampil sehingga kamu bisa kembali ke data yang barusan dibuka. Riwayat ini hanya tersimpan sementara di browser — hilang saat halaman dimuat ulang, dan tidak pernah dikirim ke server. Ada tombol 'Bersihkan' untuk menghapusnya kapan saja.",
      "Ormawa Visit yang sudah diarsipkan kini ditandai spanduk abu-abu di atas layar (warnanya sengaja dibedakan dari spanduk kuning Mode Demo), lengkap dengan penjelasan berbeda untuk admin dan peran lain.",
      "Timeline: garis bantu vertikal kini melintas di BELAKANG kolom nama tugas, bukan menimpanya.",
      "Timeline: kotak tanggal yang mengikuti kursor kini tetap terlihat di bagian atas layar walau kamu menggulir jauh ke bawah — berguna saat tugasnya banyak.",
      "PERBAIKAN: pemilih peran di Mode Demo lokal sempat tidak berfungsi (menunya muncul, tapi diklik tidak mengubah apa pun).",
    ],
  },
  {
    version: "1.20.0",
    date: "2026-07-28",
    title: "Perbaikan besar izin menyimpan, arsip Ormawa Visit, backup, & keamanan",
    changes: [
      "PERBAIKAN PENTING: Koordinator, Staff, dan Intern sebelumnya bisa gagal menyimpan TANPA pesan apa pun — datanya tampil di layar lalu hilang saat halaman dimuat ulang. Penyebabnya aturan database masih mengira setiap akun terikat pada satu divisi dan satu Ormawa Visit, padahal akun di sistem ini tidak pernah begitu. Aturan itu sudah dihapus.",
      "Izin menyimpan kini hanya ditentukan oleh PERAN, persis seperti tabel Matriks Akses di Pengaturan. Staff & Intern bisa membuat dan mengubah tugas divisi mana pun, tapi tetap tidak bisa menghapus.",
      "Setiap kegagalan menyimpan kini SELALU memunculkan pesan merah. Sebelumnya 37 jenis penyimpanan (rundown, Hari-H, Super Link, Reach & Offer, divisi, FAQ, anggaran, dan lainnya) diam saja ketika gagal.",
      "BARU — Arsip Ormawa Visit: admin bisa mengunci Ormawa Visit yang sudah selesai lewat menu titik-tiga di halaman Daftar Ormawa Visit. Setelah dikunci, tidak ada peran lain yang bisa mengubah apa pun di dalamnya. Admin tetap bisa memperbaiki isinya dan membuka kuncinya kapan saja.",
      "Backup otomatis terjadwal ternyata TIDAK PERNAH berhasil sejak pengetatan keamanan — setiap kali jalan, isinya kosong. Sekarang sudah berfungsi, dan backup yang kosong ditolak agar tidak menimpa riwayat backup yang baik.",
      "Pemulihan (restore) sebelumnya menghapus permanen semua tautan hasil tugas. Sekarang tautan tersebut ikut tercadangkan dan dipulihkan.",
      "Akun yang baru mendaftar dan belum disetujui perannya kini benar-benar tidak bisa membaca Anggaran dan Super Link, sesuai Matriks Akses.",
      "Penguatan keamanan: penambahan header proteksi standar (anti-clickjacking, anti-penyadapan konten), cookie aplikasi tidak lagi bisa dibaca skrip halaman, dan kunci rahasia backup tidak lagi boleh dikirim lewat alamat URL.",
      "Halaman Anggaran tidak lagi memunculkan galat tersembunyi di setiap pembukaan halaman.",
      "BARU — Pencarian global: tekan Ctrl+K (atau ⌘K), atau ketik “/”, untuk mencari tugas, anggota, divisi, Reach & Offer, Super Link, anggaran, rundown, Hari-H, dan FAQ sekaligus. Gunakan panah atas/bawah lalu Enter untuk langsung membuka hasilnya. Hasil hanya menampilkan menu yang boleh kamu buka.",
      "Backup otomatis dihapus sepenuhnya — backup kini murni manual lewat tombol di Pengaturan. Tidak ada lagi kunci rahasia yang perlu dikonfigurasi.",
      "PERBAIKAN: mengubah Fokus Divisi ke satu divisi lalu kembali ke “Semua Divisi” membuat seluruh daftar tugas hilang sampai halaman dimuat ulang. Sekarang langsung kembali normal.",
      "Timeline diperbaiki menyeluruh: garis tugas kini benar-benar sejajar dengan tanggal di atasnya, sumbu menampilkan tanggal harian (bukan hanya nama bulan), garis liar di sisi kiri hilang, timeline bisa digeser ke samping dengan kolom nama tugas yang tetap menempel, ada penanda “Hari ini”, garis bantu tanggal yang mengikuti kursor, dan info lengkap tugas saat kursor diarahkan ke batangnya.",
      "Bulatan kecil penanda status tidak lagi gepeng saat judul tugasnya panjang.",
    ],
  },
  {
    version: "1.19.0",
    date: "2026-07-27",
    title: "Divisi & Anggota menyatu, warna kategori anggaran, & perbaikan kolom Qty",
    changes: [
      "Divisi dan Anggota kini benar-benar terhubung: begitu seorang anggota diberi divisi di tab Anggota EA, namanya otomatis muncul pada 'Struktur Tim' di kartu divisi tersebut. Tidak ada lagi daftar anggota yang harus diketik dua kali.",
      "Satu orang boleh berada di LEBIH DARI SATU divisi. Pilihan divisi pada formulir anggota kini berupa daftar centang, dan semua divisinya ditampilkan di tabel Anggota EA.",
      "Koordinator hanya bisa dipilih dari fungsionaris divisi yang bersangkutan, dan sebuah divisi boleh tidak punya koordinator sama sekali.",
      "Kartu divisi kini menampilkan jumlah anggotanya di samping jumlah tugas.",
      "Anggaran: warna bulatan kecil pada kategori bisa diubah — lewat pop-up 'Tambah Item' maupun langsung dari bulatannya, memakai pilihan warna yang sama dengan pengaturan warna divisi.",
      "Anggaran: kolom Qty & Harga kini tersimpan saat menekan Enter, dan tombol panah naik/turun ikut tersimpan sendiri sesaat setelah diklik (sebelumnya baru tersimpan kalau mengklik di luar kolom). Tekan Esc untuk membatalkan.",
      "Panduan: ikon panah pada 'Panduan Lengkap per Fitur' diganti agar sama rapi dengan panah di FAQ.",
      "Role Request: menu ini kini menjelaskan sendiri kenapa pengajuan peran tidak bisa berjalan di Mode Demo.",
    ],
  },
  {
    version: "1.18.1",
    date: "2026-07-26",
    title: "Perbaikan internal: keamanan migrasi, kecepatan muat, & stabilitas",
    changes: [
      "Halaman terasa lebih ringan: kamus terjemahan Inggris (33KB) tidak lagi ikut diunduh oleh pengguna berbahasa Indonesia.",
      "Perbaikan penting pada urutan migrasi database — pengetatan izin tugas sempat bisa terbatalkan; kini dipulihkan dan tidak mengunci akses Koordinator/Staff/Intern.",
      "Menyimpan satu data tidak lagi menyegarkan seluruh halaman aplikasi, hanya halaman yang memakainya.",
      "Formulir tidak lagi berkedip saat dibuka (pengisian ulang dilakukan tanpa efek samping).",
      "Penambahan pengujian otomatis untuk seluruh alur izin Server Action; semua peringatan kualitas kode dibersihkan.",
    ],
  },
  {
    version: "1.18.0",
    date: "2026-07-26",
    title: "Kebijakan Privasi & Ketentuan Layanan",
    changes: [
      "Halaman Kebijakan Privasi baru: menjelaskan data apa yang dikumpulkan (akun, keanggotaan, pekerjaan, himpunan mitra), cookie yang dipakai, siapa yang bisa melihat apa, dan hak kamu atas datamu.",
      "Halaman Ketentuan Layanan baru: aturan pemakaian akun, larangan penyalahgunaan data himpunan mitra, ketentuan Mode Demo, dan batasan tanggung jawab.",
      "Kedua halaman bisa dibuka tanpa akun (dari halaman Masuk/Daftar) dan tersedia dalam Bahasa Indonesia serta English mengikuti tombol bahasa.",
      "Tautan ke kedua dokumen ditambahkan di footer aplikasi, halaman Masuk, dan halaman Daftar.",
      "Halaman Daftar kini mencantumkan pernyataan bahwa mendaftar berarti menyetujui Ketentuan Layanan dan Kebijakan Privasi.",
    ],
  },
  {
    version: "1.16.0",
    date: "2026-07-26",
    title: "Perbaikan hak akses tugas, pengajuan peran yang bisa diubah & rundown",
    changes: [
      "Perbaikan penting: Staff & Intern kini bisa mengubah dan mengisi hasil SEMUA tugas, bukan cuma sebagian. Sebelumnya hak akses ikut terkunci ke divisi di profil akun, sehingga tugas divisi lain tidak bisa disentuh.",
      "Anggaran dan Pengaturan kini bisa dibuka Koordinator, Staff, dan Intern dalam mode hanya-lihat. Backup, rollback, dan reset data demo tetap khusus Admin.",
      "Pengajuan peran tidak lagi meminta pilihan Ormawa Visit — satu peran berlaku untuk semua Ormawa Visit.",
      "Pengajuan peran yang masih menunggu keputusan sekarang bisa diperbaiki dan dikirim ulang lewat 'Ubah pengajuan'.",
      "Akun yang sudah punya peran bisa mengajukan perubahan peran (naik atau turun). Peran yang sedang dipakai tidak muncul sebagai pilihan, Admin tidak bisa diminta lewat pengajuan, dan akun Admin tidak bisa diturunkan.",
      "Rundown: kolom Durasi kini otomatis terisi untuk semua baris yang punya waktu mulai & selesai, termasuk baris lama yang sebelumnya kosong.",
      "Rundown: kolom beku (No, Waktu, Durasi, Kegiatan) tidak lagi tampak berlubang saat tabel digeser — lebar kolom kini dikunci sehingga posisi bekunya selalu pas.",
    ],
  },
  {
    version: "1.15.0",
    date: "2026-07-26",
    title: "Akses Terbatas, daftar akun sendiri, permintaan peran & menu samping yang bisa diciutkan",
    changes: [
      "Tingkat akses baru 'Akses terbatas' (centang kuning): bisa membuat, mengubah, dan mengisi hasil — tapi tidak bisa menghapus.",
      "Staff & Intern kini punya Akses terbatas di Work Breakdown, Rundown, Hari-H, dan Super Link.",
      "Koordinator tetap akses penuh di keempat menu itu, dan menjadi hanya-lihat di menu lainnya (Anggaran, Reach & Offer, Divisi & Anggota, FAQ, Ormawa Visit).",
      "Matriks Hak Akses di Pengaturan sekarang punya empat status: penuh (hijau), terbatas (kuning), hanya lihat (biru), tidak ada akses (strip).",
      "Menu samping bisa diciutkan menjadi ikon saja lewat tombol panel — dan otomatis terbuka sementara saat kursor diarahkan ke bilah ikon. Pilihanmu diingat.",
      "Halaman Daftar baru: bikin akun sendiri pakai email & kata sandi, atau lewat Google. Masuk dengan Google juga tersedia.",
      "Akun yang baru mendaftar belum punya peran (setara Tamu) dan bisa mengajukan peran Koordinator / Staff / Intern lewat menu akun atau spanduk di atas halaman.",
      "Menu baru 'Role Request' (khusus Admin): daftar akun yang mengajukan peran, lengkap dengan tombol Setujui dan Abaikan.",
    ],
  },
  {
    version: "1.14.0",
    date: "2026-07-20",
    title: "Perbaikan Mode Demo, status otomatis Overtime, & rundown",
    changes: [
      "Mode Demo: ubah status & simpan hasil tugas kini berfungsi (skrip akses demo diperbarui agar bisa menulis, bukan hanya membaca).",
      "Status tugas otomatis menjadi 'Overtime' bila melewati tenggat dan belum selesai — pengecekan berlaku setiap kali data dibuka.",
      "Rundown: kolom beku (No/Waktu/Durasi/Kegiatan) tidak lagi tampak tembus pandang saat tabel digeser.",
      "Reset data Mode Demo kini benar-benar mengembalikan SEMUA data, termasuk Ormawa Visit yang kamu buat.",
      "Aksi massal status tugas kini menampilkan pesan bila gagal, tidak diam-diam.",
      "Staff & Intern dapat memperbarui status dan mengisi hasil pada tugas divisinya (perbaikan izin database).",
    ],
  },
  {
    version: "1.13.0",
    date: "2026-07-20",
    title: "Perbaikan Work Breakdown & fitur data utama Reach & Offer",
    changes: [
      "Perbaikan penting: ubah status tugas dan simpan hasil kini berfungsi kembali (kesalahan tersembunyi dari database/izin sekarang ditampilkan, bukan diam-diam gagal).",
      "PIC tugas: dropdown kini hanya menampilkan anggota divisi tersebut, dikelompokkan Koordinator / Fungsionaris / Intern.",
      "Reach & Offer: PIC dipilih dari anggota EA; Lokasi & Mode dipisah; prospek yang selesai tampil berbeda di tabel.",
      "Reach & Offer: tandai satu prospek sebagai 'data utama' Ormawa Visit — data OV (partner, kampus, lokasi, mode) otomatis mengikuti, dan hanya boleh satu per OV.",
      "Rundown: dijadikan satu versi (versi B dihapus); kolom No/Waktu/Durasi/Kegiatan dibekukan; tombol buka tautan pada Kebutuhan Operator.",
      "Ormawa Visit baru: form tidak lagi mengisi otomatis detail yang masih rencana (partner, tipe, mode); menyusul dari prospek utama.",
      "Panduan: 'Alur Singkat' dan 'Panduan Lengkap' dipisah dengan tombol.",
      "Mode Demo: nama pengguna kini sesuai peran (Admin, Koordinator, dst.).",
      "Perbaikan tampilan: kotak singkatan divisi kini selalu persegi.",
    ],
  },
  {
    version: "1.12.0",
    date: "2026-07-20",
    title: "Hasil tugas terstruktur, sinkron Super Link, & panduan lengkap",
    changes: [
      "Hasil tugas kini dipisah: kolom deskripsi + daftar tautan tersendiri, bisa lebih dari satu tautan.",
      "Setiap tautan hasil divalidasi (wajib http:// atau https://) dan tidak boleh sama dua kali dalam satu tugas.",
      "Tautan hasil bisa ditampilkan di Super Link lengkap dengan nama tautannya — cukup centang saat mengisi hasil.",
      "Tautan yang tampil di Super Link tidak akan terduplikat walau tugas disimpan berkali-kali; mengubah atau menghapus tautan di tugas otomatis memperbarui Super Link, dan menghapus tugas ikut menghapus tautannya.",
      "Panduan: ditambah bagian 'Panduan Lengkap per Fitur' berisi tujuan, langkah pemakaian, hal penting, dan hak akses tiap menu.",
      "Seluruh isi panduan tersedia dalam Bahasa Indonesia dan English, mengikuti tombol bahasa.",
    ],
  },
  {
    version: "1.11.0",
    date: "2026-07-20",
    title: "Sortir bertingkat, duplikat, & penyegaran tampilan",
    changes: [
      "Pengurutan tabel kini bertingkat: klik kolom kedua tidak lagi menghapus urutan kolom pertama — urutan prioritas ditampilkan dengan angka (klik ketiga menghapus kolom itu dari urutan).",
      "Tombol 'Duplikat' ditambahkan pada Tugas, item Anggaran, baris Rundown, Job Hari-H, dan Ormawa Visit.",
      "Work Breakdown: kolom Hasil tidak lagi bisa diketik langsung di tabel — isi lewat pop-up tugas agar tidak tertimpa tak sengaja.",
      "Work Breakdown: tombol 'Simpan & Selesai' untuk menyimpan sekaligus menandai tugas selesai.",
      "Work Breakdown: pemilih 'Fokus divisi' dipindah dari pojok kanan atas ke toolbar Work Breakdown, bersama filter lainnya.",
      "Kalender: ikon plus muncul di pojok kanan atas tanggal saat disorot untuk menambah tugas di tanggal itu.",
      "Daftar Ormawa Visit: tiap kartu punya tombol untuk langsung menjadikannya Ormawa Visit yang sedang dilihat.",
      "Dashboard: Akses Cepat dipindah ke bagian atas dengan tampilan geser (carousel).",
      "Dashboard: diagram donat diperbarui — arahkan kursor ke tiap bagian untuk melihat jumlah & persentasenya.",
      "Divisi & Anggota: Struktur Tim kini menyatu di kartu divisi (koordinator, fungsionaris, dan intern langsung terlihat & bisa diubah dari sana).",
    ],
  },
  {
    version: "1.10.1",
    date: "2026-07-20",
    title: "Perbaikan: gagal kembali ke halaman login & kebocoran akses saat ganti peran",
    changes: [
      "Membuka situs tanpa sesi login (mis. dari perangkat lain) kini benar diarahkan ke halaman Masuk, tidak lagi menampilkan error di dashboard.",
      "Halaman Anggaran, Super Link, dan Pengaturan kini benar-benar tertutup untuk peran yang tidak berhak — termasuk saat berganti peran sambil membuka halaman tersebut.",
      "Sistem tidak lagi gagal total saat daftar Ormawa Visit kosong atau belum bisa diakses.",
    ],
  },
  {
    version: "1.10.0",
    date: "2026-07-20",
    title: "Menu Divisi & Anggota digabung, multi-select, & drag-and-drop Hari-H",
    changes: [
      "Menu 'Divisi' dan 'Anggota & Tim' digabung menjadi satu menu 'Divisi & Anggota' dengan tab Divisi, Anggota, dan Struktur Tim.",
      "Daftar Divisi kini bisa multi-select untuk hapus massal atau ubah status ikut/tanpa rundown sekaligus.",
      "Job Hari-H kini bisa diurutkan dengan drag-and-drop; nomor tersusun otomatis.",
      "Reach & Offer, Super Link, dan item Anggaran kini bisa multi-select untuk hapus massal.",
      "Mode Demo: opsi Backup diganti dengan 'Reset ke data awal' untuk mengembalikan sandbox ke contoh semula.",
    ],
  },
  {
    version: "1.9.0",
    date: "2026-07-20",
    title: "Koordinator sebagai peran & data roster asli",
    changes: [
      "Koordinator kini menjadi peran (atasan) di dalam divisi, bukan divisi tersendiri — setiap divisi punya satu koordinator pada struktur tim.",
      "Data divisi, anggota, dan struktur tim diisi dengan data asli External Affairs untuk tiap Ormawa Visit (nama dipertahankan apa adanya).",
      "Divisi tiap Ormawa Visit kini persis sesuai struktur tim aslinya; divisi lama yang tidak sesuai dihapus.",
      "Angkatan anggota otomatis dari NRP; panggilan mengikuti nama yang ditulis atau kata pertama nama.",
      "Catatan: tugas lama pada divisi yang dihapus (mis. PIC/Coordinator) tetap ada namun tanpa label divisi sampai ditata ulang.",
    ],
  },
  {
    version: "1.8.0",
    date: "2026-07-20",
    title: "Divisi & anggota kini per Ormawa Visit",
    changes: [
      "Divisi sekarang milik masing-masing Ormawa Visit — tiap OV bisa punya nama, singkatan, warna, dan susunan divisi sendiri tanpa memengaruhi OV lain.",
      "Anggota & tim juga per Ormawa Visit; roster lama otomatis ditautkan ke Ormawa Visit paling awal.",
      "Template pembuatan OV baru kini bisa ikut menyalin Divisi dan Anggota & Tim dari OV sumber.",
      "Data lama tetap aman: divisi yang sebelumnya dipakai bersama disalin ke tiap OV yang sudah ada, jadi semua tugas tetap terhubung ke divisinya.",
    ],
  },
  {
    version: "1.7.0",
    date: "2026-07-20",
    title: "Penguatan keamanan, validasi, & ketepatan data",
    changes: [
      "Keamanan: data (termasuk NRP anggota) tidak lagi bisa dibaca tanpa sesi login; Mode Tamu kini memakai sesi anonim sehingga tetap bisa melihat tanpa membuka data ke publik.",
      "Hak akses database (RLS) diselaraskan dengan aturan aplikasi: Koordinator kini benar-benar bisa mengelola rundown, job hari-H, & struktur tim; Staff/Intern hanya bisa menambah Super Link, bukan mengubah/menghapus milik orang lain.",
      "Semua input Reach & Offer, Super Link, Rundown, Job Hari-H, dan Tim kini divalidasi penuh (anti data rusak & field liar).",
      "Anggaran: perhitungan total dibulatkan ke rupiah utuh (tidak ada lagi angka desimal aneh), dan kolom tidak menerima nilai negatif.",
      "Penomoran tugas & job hari-H kini otomatis dan aman dari tabrakan saat dua orang menambah bersamaan.",
      "Aksi massal tugas kini memberi tahu jika ada tugas yang dilewati karena tanpa akses.",
      "Nama & panggilan anggota tidak boleh mengandung koma (mencegah kesalahan pemilihan PIC/anggota tim).",
      "Berbagai perbaikan performa & konsistensi data internal.",
    ],
  },
  {
    version: "1.6.1",
    date: "2026-07-20",
    title: "Identitas baru, penyempurnaan rundown & divisi",
    changes: [
      "Nama sistem menjadi 'Ormawa Visit Management System' dengan logo & favicon baru yang lebih profesional.",
      "Rundown: field kegiatan kini menyesuaikan tinggi (teks panjang tidak lagi terpotong); kolom MC & Kebutuhan Operator dipindah ke samping Kegiatan.",
      "Rundown: durasi otomatis dihitung dari waktu, dan kegiatan baru otomatis dimulai dari waktu selesai kegiatan sebelumnya.",
      "Divisi: singkatan Coordinator diperbaiki menjadi 'CORD'; PIC, Coordinator, Secretary, Treasurer kini tidak diikutkan pada rundown.",
      "Divisi: penataan pemilih warna dirapikan pada dialog edit.",
      "Penomoran versi kini tanpa nama kode.",
    ],
  },
  {
    version: "1.6.0",
    date: "2026-07-20",
    title: "Rundown tabel dinamis, Panduan, FAQ CRUD, & penyempurnaan divisi",
    changes: [
      "Rundown dirombak menjadi tabel: tiap divisi otomatis menjadi kolom, kegiatannya diisi langsung di tabel. MC & Kebutuhan Operator tetap kolom tetap; kolom pengisi acara dihapus.",
      "Rundown: edit & hapus langsung di tabel (tanpa menu titik tiga), plus catatan cepat 'terlalu cepat/lama [menit]'.",
      "Divisi: tambah opsi edit & hapus, singkatan otomatis kapital maksimal 4 huruf, dan opsi 'tidak diikutsertakan pada rundown'.",
      "Anggota & Tim: kolom kini bisa diurutkan (sorting).",
      "FAQ kini bisa CRUD penuh (tambah/edit/hapus), dan Panduan dipisah ke menu tersendiri.",
      "Panduan: flowchart alur penggunaan website dari awal sampai akhir, lengkap dengan percabangan keputusan.",
    ],
  },
  {
    version: "1.5.0",
    date: "2026-07-19",
    title: "Mode Demo, template pembuatan, & integrasi anggota",
    changes: [
      "Mode Demo: sandbox dengan database Supabase terpisah — dari halaman login, coba-coba tanpa akun. Data demo dan data asli benar-benar terisolasi (tidak bisa saling mengakses).",
      "Template pembuatan Ormawa Visit: saat membuat edisi baru, data (tugas, rundown, job hari-H, struktur tim, anggaran) bisa disalin dari Ormawa Visit sebelumnya, tidak lagi diisi satu per satu.",
      "PIC tugas & job hari-H kini dipilih langsung dari daftar anggota, bukan diketik manual.",
      "Anggota & Tim: pilih banyak anggota sekaligus untuk hapus atau ubah divisi/tipe massal.",
      "Angkatan anggota kini otomatis dari NRP (mis. 5026(23)1128 → angkatan 2023).",
      "Data anggaran Ormawa Visit 'HMSI ITS x HMD Eksternal' yang keliru dihapus.",
      "Skema versi diseragamkan menjadi v1.x.y dan matriks hak akses membedakan akses penuh, hanya-lihat, dan tanpa akses.",
    ],
  },
  {
    version: "1.4.0",
    date: "2026-07-18",
    title: "Perombakan besar: penomoran otomatis, RAB & Anggota penuh CRUD, backup",
    changes: [
      "Penomoran tugas & Hari-H sekarang otomatis; ID lama dari spreadsheet dihapus.",
      "Super Link dirombak: dikelompokkan per Ormawa Visit & divisi, wajib memiliki URL.",
      "Anggaran (RAB) kini bisa CRUD penuh: tambah/hapus rencana & item.",
      "Anggota EA kini tampil per Ormawa Visit, tampilan tabel, divisi wajib diisi.",
      "Struktur Tim: pengisian anggota via dropdown multi-select, bukan teks bebas lagi.",
      "Fitur reset ke data Excel awal dihapus; digantikan Backup & Rollback.",
      "Backup manual, backup otomatis terjadwal, dan pemulihan (rollback) data.",
      "Palet warna divisi diurutkan + ditambah versi warna muda.",
      "Berbagai perbaikan teks & kejelasan field wajib di seluruh formulir.",
    ],
  },
  {
    version: "1.3.0",
    date: "2026-07-18",
    title: "Optimasi performa navigasi",
    changes: [
      "Tambah skeleton loading agar perpindahan menu terasa instan.",
      "Kurangi query berulang ke Supabase lewat cache per-request.",
      "Proxy tidak lagi memvalidasi sesi saat prefetch (mencegah rate limit).",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-07-18",
    title: "Multi-select tugas & pengalih bahasa",
    changes: [
      "Work Breakdown: pilih banyak tugas sekaligus untuk ubah status/hapus massal.",
      "Tombol ganti bahasa Indonesia/English di sebelah tombol tema.",
      "Reach & Offer dan Super Link kini bisa difilter per Ormawa Visit.",
      "Upload file/foto untuk hasil tugas (kemudian dihapus di 2.0.0).",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-07-17",
    title: "Terhubung ke Supabase & deploy",
    changes: [
      "Sistem login sungguhan (email & password) via Supabase Auth.",
      "Mode Tamu (lihat saja, tanpa akun).",
      "Data dipindahkan dari mode demo lokal ke database Supabase cloud.",
      "Perbaikan data Super Link yang sebelumnya berupa shortcut, bukan URL asli.",
      "Panduan & konfigurasi deployment ke Vercel.",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-07-16",
    title: "Peluncuran awal",
    changes: [
      "Sistem dibangun dari digitalisasi Main Sheet Ormawa Visit (Google Sheets).",
      "Dashboard, Work Breakdown Structure, Papan Divisi, Reach & Offer, Anggaran, Super Link.",
      "Kalender, Rundown Acara, Job Hari-H, Anggota & Tim, Edisi Ormawa Visit, FAQ.",
      "Hak akses berjenjang: Admin/PIC, Koordinator, Staff, Intern, Tamu.",
    ],
  },
];
