-- ============================================================
-- 0019 — Replace divisions / members / teams with HMSI EA's real per-OV roster.
-- Generated by scripts/gen-real-roster.mjs — do not edit by hand.
--
-- Divisions become STRICT per OV; existing tasks are left as-is (tasks under a
-- removed division lose their badge, by design). "Koordinator" is a per-division
-- role on teams.coordinator. Run after 0001-0018.
-- ============================================================
begin;

-- Coordinator role on the team (idempotent).
alter table teams add column if not exists coordinator text default '';

-- Wipe the old dummy divisions/members/teams (tasks/rundown/budget untouched).
delete from teams;
delete from members;
delete from divisions;

-- ---------- ov1-2025 ----------
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2025','LO','LIAISON OFFICER','LO','#0ea5e9',1,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2025','EVENT','ACARA','ACR','#6366f1',2,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2025','CONSUMPTION','KONSUMSI','KON','#f97316',3,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2025','OPERATIONAL','KAMZIN & LOGISTIC','KML','#10b981',4,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2025','OUTSOURCE','OUTSOURCE','OUT','#64748b',5,false) on conflict (event_id,key) do nothing;
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Arjuna Putra Kharisma','Mas Juna','5026221210','fungsionaris',2022,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Karina Filza Aafiyah','Mba Karina','5026221012','fungsionaris',2022,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Annisa Fadila Rahmawati','Mba Dila','5026221069','fungsionaris',2022,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Nisrina Kamiliya Riswanto','Nisrina','5026231111','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Natasha Yosefani Putri','Mba Tasha','5026221011','fungsionaris',2022,'CONSUMPTION');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Muhammad Fauzan','Mas Fauzan','5026221080','fungsionaris',2022,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Agung Budi Prasetya','Mas Agung','5026221176','fungsionaris',2022,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Arayzi Rayyansyah','Mas Aray','5026221194','fungsionaris',2022,'OUTSOURCE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Devika Rahman','Vika','5026231061','fungsionaris',2023,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Muhammad Dzaki Adfiz','Dzaki','5026231150','fungsionaris',2023,'CONSUMPTION');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Rahmadhona Elokpribadi Kusmawan','Dhone','5026231217','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Muhammad Daniel Alfarisi','Daniel','5026231161','fungsionaris',2023,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Irhab Faiz Hidayat','Irhab','5051231041','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Auliya Malika Idi','Aul','5026231141','fungsionaris',2023,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Mochammad Zhulmi Danovanz Hidanasukha','Juno','5026231172','fungsionaris',2023,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Fadhiil Akmal Hamizan','Fadhiil','5026231128','fungsionaris',2023,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2025','Burhan Shidqi Arrasyid','Burhan','5026231074','fungsionaris',2023,'OPERATIONAL');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2025','LO','Devika','Mba Dilla, Aul, Faiz, Devika','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2025','EVENT','Mas Juna','Fadhiil, Dona, Juno, Mba Karina, Nisrin, Mas Juna','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2025','CONSUMPTION','Mba Tasha','Dzaki, Mba Tasha','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2025','OPERATIONAL','Daniel','Burhan, Daniel, Mas Agung, Mas Fauzan','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2025','OUTSOURCE','Mas Aray','Mas Aray','');

-- ---------- ov2-2025 ----------
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov2-2025','LO','LIAISON OFFICER','LO','#0ea5e9',1,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov2-2025','EVENT','EVENT','EVE','#6366f1',2,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov2-2025','CONSUMPTION','CONSUMPTION','CON','#f97316',3,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov2-2025','OPERATIONAL','OPERATIONAL','OPR','#10b981',4,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov2-2025','CREATIVE','CREATIVE & MARKETING','CRM','#d946ef',5,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov2-2025','SECRETARY','SECRETARY','SEC','#8b5cf6',6,true) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov2-2025','TREASURER','TREASURER','TRE','#f59e0b',7,true) on conflict (event_id,key) do nothing;
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Arjuna Putra Kharisma','Mas Juna','5026221210','fungsionaris',2022,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Karina Filza Aafiyah','Mba Karina','5026221012','fungsionaris',2022,'CONSUMPTION');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Annisa Fadila Rahmawati','Mba Dila','5026221069','fungsionaris',2022,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Nisrina Kamiliya Riswanto','Nisrina','5026231111','fungsionaris',2023,'CONSUMPTION');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Natasha Yosefani Putri','Mba Tasha','5026221011','fungsionaris',2022,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Muhammad Fauzan','Mas Fauzan','5026221080','fungsionaris',2022,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Agung Budi Prasetya','Mas Agung','5026221176','fungsionaris',2022,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Arayzi Rayyansyah','Mas Aray','5026221194','fungsionaris',2022,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Devika Rahman','Vika','5026231061','fungsionaris',2023,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Muhammad Dzaki Adfiz','Dzaki','5026231150','fungsionaris',2023,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Rahmadhona Elokpribadi Kusmawan','Dhone','5026231217','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Muhammad Daniel Alfarisi','Daniel','5026231161','fungsionaris',2023,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Irhab Faiz Hidayat','Irhab','5051231041','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Auliya Malika Idi','Aul','5026231141','fungsionaris',2023,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Mochammad Zhulmi Danovanz Hidanasukha','Juno','5026231172','fungsionaris',2023,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Fadhiil Akmal Hamizan','Fadhiil','5026231128','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Burhan Shidqi Arrasyid','Burhan','5026231074','fungsionaris',2023,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Agha Aryo Utomo','Agha','5026241003','intern',2024,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Adesya Naila Salsabila','Naila','5026241004','intern',2024,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','I Gusti Ayu Anindya Septiari','Anin','5026241007','intern',2024,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Aliya Nur Kamila Silia','Ali','5026241008','intern',2024,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Audrey Sophia Malona Lumbantobing','Audrey','5026241014','intern',2024,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Faiza Aditya Zahratunnisa','Zahra','5026241017','intern',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Christine Rotua Deborah Hutabarat','Christine','5026241028','intern',2024,'CONSUMPTION');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Athilah Syahshiyah Tsabitah','Athilah','5026241031','intern',2024,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Muhammad Sandhika Setiawan','Sandhik','5026241043','intern',2024,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Mahda Vekia','Mahda','5026241050','intern',2024,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Muhammad Aqzhara Fathyan Khairi','Aqzha','5026241053','intern',2024,'CONSUMPTION');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Crystal Reinheart','Crystal','5026241055','intern',2024,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Pasha Avatar Ardan','Avatar','5026241066','intern',2024,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','A. Kezia J.I. Manurung','Kezia','5026241076','intern',2024,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Harunina Irene Syafira','Irene','5026241080','intern',2024,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Alwida Rahmat','Alwida','5026241090','intern',2024,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Claudio Huge Siburian','Claudio','5026241112','intern',2024,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Adelia Maritza Rani','Adel','5026241120','intern',2024,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Ahmad ''Aaqila Akbar','Aqil','5026241128','intern',2024,'CONSUMPTION');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Franzaldi Amarullah Nalandhika','Franz','5026241156','intern',2024,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Benedictus Nicholas Christian','Nicho','5026241187','intern',2024,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Izaaz Verdiansyah Khaisan Athif','Izaaz','5026241194','intern',2024,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Thalia Harnum Fathina','Thalia','5026241201','intern',2024,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Muhammad Armaan Andromeda Harw','Andro','5026241204','intern',2024,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Sheva Rafid Fairuz Rifa''i','Fairuz','5051241003','intern',2024,'CREATIVE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Suci Nur Aisyah','Suci','5051241013','intern',2024,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2025','Hayyu Izza M SHidqi','Hayyu','5051241024','intern',2024,null);
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov2-2025','LO','Vika','Vika, Daniel, Mba Tahe','Audrey, Irene, Kezia, Mahda, Suci');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov2-2025','EVENT','Burhan','Burhan, Juno, Mba dila, Mas Agung','Adesya, Avatar, Crystal, Franz, Haqi');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov2-2025','CONSUMPTION','Nisrina','Nisrina, Mba Karina','Aqil, Aqzha, Christine');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov2-2025','OPERATIONAL','Faiz','Faiz, Mas Aray','Ali, Andro, Nicho, Claudio, Sandhika');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov2-2025','CREATIVE','Dzaki','Dzaki, Auliya, Mas Fauzan, Mas Juna','Adel, Agha, Alwida, Anin, Athilah, Fairuz, Izaaz, Thalia');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov2-2025','SECRETARY','Nisrina','Nisrina','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov2-2025','TREASURER','Dzaki','Dzaki','');

-- ---------- ov1-2026 ----------
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2026','LO','LIAISON OFFICER','LO','#0ea5e9',1,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2026','EVENT','EVENT','EVE','#6366f1',2,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2026','CONSUMPTION','CONSUMPTION','CON','#f97316',3,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2026','OPERATIONAL','OPERATIONAL','OPR','#10b981',4,false) on conflict (event_id,key) do nothing;
insert into divisions(event_id,key,name,short,color,"order",exclude_from_rundown) values ('ov1-2026','OUTSOURCE','OUTSOURCE','OUT','#64748b',5,false) on conflict (event_id,key) do nothing;
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Auliya Malika Idi','Aul','5026231141','fungsionaris',2023,'OUTSOURCE');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Muhammad Daniel Alfarisi','Daniel','5026231161','fungsionaris',2023,'CONSUMPTION');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Burhan Shidqi Arrasyid','Burhan','5026231074','fungsionaris',2023,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Khalila Shafarayhani Atletiko','Khalila','5026231167','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Fadhiil Akmal Hamizan','Fadhiil','5026231128','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Irhab Faiz Hidayat','Irhab','5051231041','fungsionaris',2023,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Rofifah Zain Nur Alfiyah','Rofifah','5026241131','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Muhammad Izzan Aquilla','Izzan','5026241069','fungsionaris',2024,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Aliya Nur Kamila Silia','Ali','5026241008','fungsionaris',2024,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Mahda Vekia','Mahda','5026241050','fungsionaris',2024,'LO');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Naina Mazaya Putri','Naina','5026241183','fungsionaris',2024,'EVENT');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Mega Agustina Sihombing','Mega','5026241165','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Mazaya Zharfani Erfindri','Mazaya','5026241138','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Alwida Rahmat','Alwida','5026241090','fungsionaris',2024,'OPERATIONAL');
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov1-2026','Athilah Syahshiyah Tsabitah','Athilah','5026241031','fungsionaris',2024,null);
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2026','LO','Mahda','Mahda, Mba Lila','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2026','EVENT','Ali','Ali, Naina, Izzan, Mazay, Mas padil','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2026','CONSUMPTION','Atilah','Atilah, Mas daniel','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2026','OPERATIONAL','Alwida','Alwida, Mas burhan, Mas irhab','');
insert into teams(event_id,division,coordinator,fungsionaris,intern) values ('ov1-2026','OUTSOURCE','Mba Aul','Mba Aul','');

-- ---------- ov2-2026 ----------
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Auliya Malika Idi','Aul','5026231141','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Muhammad Daniel Alfarisi','Daniel','5026231161','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Burhan Shidqi Arrasyid','Burhan','5026231074','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Khalila Shafarayhani Atletiko','Khalila','5026231167','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Fadhiil Akmal Hamizan','Fadhiil','5026231128','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Irhab Faiz Hidayat','Irhab','5051231041','fungsionaris',2023,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Rofifah Zain Nur Alfiyah','Rofifah','5026241131','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Muhammad Izzan Aquilla','Izzan','5026241069','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Aliya Nur Kamila Silia','Ali','5026241008','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Mahda Vekia','Mahda','5026241050','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Naina Mazaya Putri','Naina','5026241183','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Mega Agustina Sihombing','Mega','5026241165','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Mazaya Zharfani Erfindri','Mazaya','5026241138','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Alwida Rahmat','Alwida','5026241090','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Athilah Syahshiyah Tsabitah','Athilah','5026241031','fungsionaris',2024,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Ahnaf Rayhan Nurducha','Ahnaf','5026251145','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Nastiti Ayu Lestari','Nastiti','5026251020','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Rasya Hafidz Atharachman','Rasya','5026251031','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Navita Fitrianti Refani','Navita','5026251041','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Tsabita Aulia Rakhmah','Tsabita','5026251129','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Laysya Pramitha Cahyaning Arum','Laysya','5051251033','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Zafira Najla Rinjani','Zafira','5026251059','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Ghadiza Naura Aliya','Ghadiza','5026251199','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Muhammad Mazen Ibrahim','Mazen','5026251176','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Valery Dienda Setyabudi','Valery','5026251033','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Nesda Yulditia','Nesda','5051251019','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Akbar Ariffianto','Akbar','5026251006','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Maureen Rahmania Maulana','Maureen','5051251007','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Alya Mutiara Putri','Alya','5026251021','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Priska Fiantika Widyatama','Priska','5026251170','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Refa Thalita Ardila','Refa','5026251188','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Tiara Kumala Farid','Tiara','5026251032','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Raisa Adintria Rahman','Raisa','5026251158','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Deaka Rizkia Rahma','Deaka','5026251104','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Aryo Gading Kelana','Aryo','5026251209','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Farrel Danish Virdiansyah','Farrel','5026251178','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Famya Lituhayu','Famya','5026251157','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Syofia Felanatasya Raka Yudharwita','Syofia','5026251175','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Aura Chayara Sultrawiria','Aura','5026251127','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Gahyaka Galur Widyatmana','Gahyaka','5026251029','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Ni Luh Putu Raina Pradnya Pramesty','Raina','5026251162','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Aulia Safa Az-Zahra','Aulia','5026251089','intern',2025,null);
insert into members(event_id,name,nickname,nrp,type,year,division) values ('ov2-2026','Dimas Fajar Habibi','Dimas','5026251049','intern',2025,null);

commit;
