-- ============================================================
-- 0021 — SUPERSEDED. Intentionally a no-op. Do not restore the old body.
--
-- This migration used to drop tasks_insert/tasks_update/tasks_delete and
-- recreate them as plain role checks (`auth_role() in (...)`), because after
-- divisions became per-event (0018) and were reseeded (0019), the old
-- `division = auth_division()` test no longer matched and silently blocked
-- every non-admin task write.
--
-- 0020_security_authz_hardening.sql fixes that properly: profiles gained
-- `event_id`, and the task policies now match on (event_id, division) via
-- owns_scope(). Running this file after 0020 would DROP that hardening and
-- reopen H1 (a coordinator of one Ormawa Visit writing another's tasks) and
-- H2 (staff/intern rewriting any task column).
--
-- If you already ran the old version of this file, 0026 re-asserts the correct
-- policies — run it.
-- ============================================================

-- no-op
select 1;
